jobs:
- job: BuildWindows
  displayName: 'Build Windows'
  pool:
    vmImage: windows-2019
  steps:
  - task: PowerShell@2
    displayName: Configure Build'
    inputs:
      targetType: filePath
      filePath: .\xdelta3\windowsconfig.ps1
      workingDirectory: .\xdelta3
  - task: MSBuild@1
    displayName: 'Build Project xdelta3\xdelta3.vcxproj'
    inputs:
      solution: xdelta3\xdelta3.vcxproj
      configuration: xdelta3-64
      msbuildArguments: /p:Platform=x64
  - task: ArchiveFiles@2
    displayName: 'Archive Windows'
    inputs:
      rootFolderOrFile: xdelta3\x64\xdelta3-64\xdelta3.exe
      includeRootFolder: false 
      archiveType: 7z
      archiveFile: $(Build.ArtifactStagingDirectory)\xdelta-3.0-windows.7z
  - task: PublishBuildArtifacts@1
    displayName: upload artifacts
    inputs:
      artifactName: xdelta3
      pathtoPublish: $(Build.ArtifactStagingDirectory)
